spring.application.name=backend
spring.datasource.url=jdbc:postgresql://houseclay.c3e8q0kistvr.ap-southeast-2.rds.amazonaws.com:5432/houseclay
spring.datasource.username=postgres
spring.datasource.password=houseclay2025
spring.jpa.hibernate.ddl-auto = create
server.port=8080
server.address=0.0.0.0