spring.application.name=backend
spring.datasource.url=jdbc:postgresql://houseclay.c3e8q0kistvr.ap-southeast-2.rds.amazonaws.com:5432/houseclay
spring.datasource.username=postgres
spring.datasource.password=houseclay2025
spring.jpa.hibernate.ddl-auto = create
server.port=8080
server.address=0.0.0.0
spring.elasticsearch.uris=http://ec2-54-252-175-163.ap-southeast-2.compute.amazonaws.com:9200
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=30s