import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DeviceContextProvider } from "@/providers/DeviceContextProvider";
import { DialogContextProvider } from "@/providers/DialogContextProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${inter.variable}`}>
        <DeviceContextProvider>
          <DialogContextProvider>{children}</DialogContextProvider>
        </DeviceContextProvider>
      </body>
    </html>
  );
}
