import { PaymentFilterStatus, PropertyCategory } from "@/common/enums";
import { PropertySummary } from "./components/PropertyCard";

export const userDummy = {
  name: "Ankit Biswas",
  phone: "91999 999 9999",
  onWhatsapp: true,
  phoneVerified: true,
  email: "ankitbiswas@gmail.com",
  emailVerified: false,
  connects: 32,
};

export const DUMMY_PROPERTIES: PropertySummary[] = [
  {
    id: "L1",
    category: PropertyCategory.RESALE,
    title: "3 BHK Premium Apartment For Sale In Bellandur",
    society: "Prestige Ferns Residency",
    addressLine: "Harlur Road, Landmark - Near Kasavanahalli Police Station",
    featured: true,
    exclusive: false,
    contacted: false,
    shortlisted: true,
    images: [
      { src: "/photos/House1.webp", alt: "Living room" },
      { src: "/photos/House2.webp", alt: "Dining area" },
      { src: "/photos/House3.webp", alt: "Bedroom" },
      { src: "/photos/House4.webp", alt: "Bedroom" },
    ],
    priceLabel: 16500000,
    priceSub: "₹ 9,800",
    emiLabel: 129000,
    areaLabel: 1680,
    beds: 3,
    baths: 3,
    facing: "East",
    parking: "Bike & Car",
    available: true,
    // rent/flatmate fields (not applicable)
    propertyType: null,
    furnishing: null,
    availableFrom: null,
    preferredTenants: null,
  },
  {
    id: "L2",
    category: PropertyCategory.RENT,
    title: "2 BHK Semi-Furnished For Rent In HSR Layout",
    society: "Salarpuria Serenity",
    addressLine: "Sector 2, 27th Main, Landmark - Near HSR BDA Complex",
    featured: false,
    exclusive: true,
    contacted: true,
    shortlisted: false,
    images: [
      { src: "/photos/House3.webp", alt: "Bedroom" },
      { src: "/photos/House1.webp", alt: "Living room" },
      { src: "/photos/House4.webp", alt: "Bedroom" },
      { src: "/photos/House2.webp", alt: "Dining area" },
    ],
    priceLabel: 48000,
    priceSub: "Deposit ₹ 2,00,000",
    emiLabel: null,
    areaLabel: 1150,
    beds: 2,
    baths: 2,
    facing: "North",
    parking: "Car",
    available: true,
    propertyType: "Apartment",
    furnishing: "Semi-Furnished",
    availableFrom: "Immediate",
    preferredTenants: "Family/Bachelors",
    depositLabel: 200000,
  },
  {
    id: "L3",
    category: PropertyCategory.RESALE,
    title: "4 BHK Corner Unit For Sale In Whitefield",
    society: "Brigade Cosmopolis",
    addressLine: "Varthur Main Road, Landmark - Near Forum Neighborhood Mall",
    featured: false,
    exclusive: false,
    contacted: false,
    shortlisted: true,
    images: [
      { src: "/photos/House2.webp", alt: "Dining area" },
      { src: "/photos/House4.webp", alt: "Bedroom" },
      { src: "/photos/House1.webp", alt: "Living room" },
      { src: "/photos/House3.webp", alt: "Bedroom" },
    ],
    priceLabel: 23500000,
    priceSub: "₹ 10,200/sq. ft.",
    emiLabel: 175000,
    areaLabel: 2300,
    beds: 4,
    baths: 4,
    facing: "West",
    parking: "Bike & Car",
    available: true,
    propertyType: null,
    furnishing: null,
    availableFrom: null,
    preferredTenants: null,
  },
  {
    id: "L4",
    category: PropertyCategory.FLATMATE,
    title: "Private Room In 3 BHK For Female In Koramangala",
    society: "Raheja Residency",
    addressLine: "8th Block, 80-Ft Road, Landmark - Near Wipro Park",
    featured: false,
    exclusive: true,
    contacted: false,
    shortlisted: false,
    images: [
      { src: "/photos/House4.webp", alt: "Bedroom" },
      { src: "/photos/House3.webp", alt: "Bedroom" },
      { src: "/photos/House2.webp", alt: "Dining area" },
      { src: "/photos/House1.webp", alt: "Living room" },
    ],
    priceLabel: 16500,
    priceSub: "Deposit ₹ 25,000",
    emiLabel: null,
    areaLabel: 140,
    beds: 1,
    baths: 1,
    facing: "South",
    parking: "Bike",
    available: true,
    propertyType: "Private Room",
    furnishing: "Fully-Furnished",
    availableFrom: "Immediate",
    preferredTenants: "Female",
    depositLabel: 25000,
  },
  {
    id: "L5",
    category: PropertyCategory.RENT,
    title: "3 BHK Lakeview Apartment For Rent In Sarjapur Road",
    society: "SJR Palazza City",
    addressLine: "Carmelaram, Landmark - Near Wipro SEZ",
    featured: false,
    exclusive: false,
    contacted: true,
    shortlisted: true,
    images: [
      { src: "/photos/House2.webp", alt: "Dining area" },
      { src: "/photos/House1.webp", alt: "Living room" },
      { src: "/photos/House3.webp", alt: "Bedroom" },
      { src: "/photos/House4.webp", alt: "Bedroom" },
    ],
    priceLabel: 68000,
    priceSub: "Maintenance ₹ 4,500/mo • Deposit ₹ 3,00,000",
    emiLabel: null,
    areaLabel: 1560,
    beds: 3,
    baths: 3,
    facing: "East",
    parking: "Bike & Car",
    available: true,
    propertyType: "Apartment",
    furnishing: "Semi-Furnished",
    availableFrom: "2025-09-01",
    preferredTenants: "Family",
    depositLabel: 300000,
  },
  {
    id: "L6",
    category: PropertyCategory.RESALE,
    title: "2 BHK Compact Home For Sale In JP Nagar",
    society: "Purva Highlands",
    addressLine: "9th Phase, Landmark - Near Brigade Millennium",
    featured: true,
    exclusive: false,
    contacted: false,
    shortlisted: false,
    images: [
      { src: "/photos/House3.webp", alt: "Bedroom" },
      { src: "/photos/House2.webp", alt: "Dining area" },
      { src: "/photos/House1.webp", alt: "Living room" },
      { src: "/photos/House4.webp", alt: "Bedroom" },
    ],
    priceLabel: 9400000,
    priceSub: "₹ 8,600/sq. ft.",
    emiLabel: 68750,
    areaLabel: 1090,
    beds: 2,
    baths: 2,
    facing: "North",
    parking: "Car",
    available: true,
    propertyType: null,
    furnishing: null,
    availableFrom: null,
    preferredTenants: null,
  },
  {
    id: "L7",
    category: PropertyCategory.FLATMATE,
    title: "Shared Room In 2 BHK For Male In Electronic City",
    society: "Ajmera Infinity",
    addressLine: "Neeladri Road, Phase 1, Landmark - Near Hypercity",
    featured: false,
    exclusive: false,
    contacted: true,
    shortlisted: false,
    images: [
      { src: "/photos/House1.webp", alt: "Living room" },
      { src: "/photos/House4.webp", alt: "Bedroom" },
      { src: "/photos/House2.webp", alt: "Dining area" },
      { src: "/photos/House3.webp", alt: "Bedroom" },
    ],
    priceLabel: 19500,
    priceSub: "Deposit ₹ 15,000",
    emiLabel: null,
    areaLabel: 110,
    beds: 1,
    baths: 1,
    facing: "West",
    parking: "Bike",
    available: false,
    propertyType: "Shared Room",
    furnishing: "Furnished",
    availableFrom: "2025-08-20",
    preferredTenants: "Male",
    depositLabel: 15000,
  },
];

export const MY_DUMMY_PROPERTIES = [
  {
    propertyID: "p1",
    propertyName: "3 BHK Premium Apartment For Sale In Bellandur",
    category: PropertyCategory.RESALE,
    listedOn: "10-Jan-2025",
    builtupArea: "1,100 sqft",
    price: "₹ 2.3 Cr",
    status: "Active",
  },
  {
    propertyID: "p2",
    propertyName: "2 BHK Semi-Furnished For Rent In HSR Layout",
    category: PropertyCategory.RENT,
    listedOn: "10-Jan-2025",
    builtupArea: "1,100 sqft",
    price: "₹ 8 Cr",
    status: "Active",
  },
  {
    propertyID: "p3",
    propertyName: "Shared Room In 2 BHK For Male In Electronic City",
    category: PropertyCategory.FLATMATE,
    listedOn: "10-Jan-2025",
    builtupArea: "2,180 sqft",
    price: "₹ 8 Cr",
    status: "Inactive",
  },
];

export const DUMMY_PAYMENTS = [
  {
    id: "1",
    type: "Basic Blue Bundle",
    dateTime: "2025-06-24T18:30:00.000+00:00",
    connects: 10,
    amount: "891",
    status: PaymentFilterStatus.COMPLETED,
    invoice: true,
  },
  {
    id: "2",
    type: "Custom Connects",
    dateTime: "2025-06-24T18:30:00.000+00:00",
    connects: 5,
    amount: "495",
    status: PaymentFilterStatus.CANCELLED,
    invoice: true,
  },
  {
    id: "3",
    type: "Priority Listing",
    dateTime: "2025-06-24T18:30:00.000+00:00",
    connects: null,
    amount: "999",
    status: PaymentFilterStatus.CANCELLED,
    invoice: false,
  },
];
