services:
  postgres-db:
    image: postgres:16-alpine
    container_name: houseclay-db
    environment:
      POSTGRES_DB: houseclay_local
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d houseclay_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: houseclay-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: houseclay-pgadmin
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  backend-app:
    build: .
    container_name: houseclay-backend
    depends_on:
      postgres-db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      # - SPRING_PROFILES_ACTIVE=local
      - DATABASE_URL=jdbc:postgresql://postgres-db:5432/houseclay_local

volumes:
  postgres_data:
  es_data:
  pgadmin_data:
