-- Seed initial non-disposable denied domains from Constants.java
-- Auto-generated with titles via JS script

INSERT INTO corporate_domain (domain_name, status, website_title, created_at, updated_at) VALUES 
('gmail.com', 'DENIED', 'Gmail', NOW(), NOW()),
('googlemail.com', 'DENIED', 'Gmail', NOW(), NOW()),
('yahoo.com', 'DENIED', 'Yahoo | Mail, Weather, Search, Politics, News, Finance, Sports &amp; Videos', NOW(), NOW()),
('yahoo.co.in', 'DENIED', 'Yahoo Search - Web Search', NOW(), NOW()),
('yahoo.in', 'DENIED', 'Yahoo Search - Web Search', NOW(), NOW()),
('yahoo.co.uk', 'DENIED', '[Fetch Failed] Yahoo', NOW(), NOW()),
('ymail.com', 'DENIED', 'Yahoo Mail | Email with smart features and top-notch security', NOW(), NOW()),
('rocketmail.com', 'DENIED', 'Yahoo Mail | Email with smart features and top-notch security', NOW(), NOW()),
('hotmail.com', 'DENIED', 'Outlook', NOW(), NOW()),
('hotmail.co.in', 'DENIED', '[Fetch Failed] Hotmail', NOW(), NOW()),
('hotmail.co.uk', 'DENIED', 'Outlook', NOW(), NOW()),
('outlook.com', 'DENIED', 'Outlook', NOW(), NOW()),
('outlook.in', 'DENIED', 'Outlook', NOW(), NOW()),
('live.com', 'DENIED', 'Outlook', NOW(), NOW()),
('msn.com', 'DENIED', 'MSN', NOW(), NOW()),
('aol.com', 'DENIED', 'News, Politics, Sports, Mail &amp; Latest Headlines - AOL.com', NOW(), NOW()),
('icloud.com', 'DENIED', 'iCloud', NOW(), NOW()),
('me.com', 'DENIED', 'iCloud', NOW(), NOW()),
('mac.com', 'DENIED', 'Mac - Apple', NOW(), NOW()),
('hey.com', 'DENIED', 'HEY — A delightfully fresh take on email + calendar, from 37signals', NOW(), NOW()),
('hushmail.com', 'DENIED', 'Hushmail: Encrypted Email and E-Signable Forms', NOW(), NOW()),
('rediffmail.com', 'DENIED', 'Rediff.com: News | Rediffmail | Stock Quotes | Rediff Gurus', NOW(), NOW()),
('rediff.com', 'DENIED', 'Rediff.com: News | Rediffmail | Stock Quotes | Rediff Gurus', NOW(), NOW()),
('sify.com', 'DENIED', 'Sify - Find engaging, reader-friendly Tech stories', NOW(), NOW()),
('indiatimes.com', 'DENIED', 'Indiatimes: Latest in Lifestyle, Health, Fashion, and Wellness', NOW(), NOW()),
('zapak.com', 'DENIED', 'Play Best Free Games Online, New Game - Zapak', NOW(), NOW()),
('in.com', 'DENIED', '[Fetch Failed] In', NOW(), NOW()),
('bsnl.in', 'DENIED', '[Fetch Failed] Bsnl', NOW(), NOW()),
('mtnl.net.in', 'DENIED', '[Fetch Failed] Mtnl', NOW(), NOW()),
('hathway.com', 'DENIED', 'Hathway: Best Service Provider for Fiber WiFi, Broadband &amp; Digital TV', NOW(), NOW()),
('zoho.com', 'DENIED', 'Zoho | Cloud Software Suite for Businesses', NOW(), NOW()),
('zoho.in', 'DENIED', 'Zoho | Cloud Software Suite for Businesses', NOW(), NOW()),
('yandex.com', 'DENIED', 'Yandex — fast Internet search', NOW(), NOW()),
('yandex.ru', 'DENIED', '[Fetch Failed] Yandex', NOW(), NOW()),
('protonmail.com', 'DENIED', 'Proton Mail: Get a free email account with privacy and encryption | Proton', NOW(), NOW()),
('proton.me', 'DENIED', 'Proton: Privacy by default', NOW(), NOW()),
('pm.me', 'DENIED', 'Proton Mail: Get a free email account with privacy and encryption | Proton', NOW(), NOW()),
('tutanota.com', 'DENIED', 'Tuta: Turn ON privacy for free with secure emails, calendars &amp; contacts | Tuta', NOW(), NOW()),
('tutanota.de', 'DENIED', 'Tuta: Turn ON privacy for free with secure emails, calendars &amp; contacts | Tuta', NOW(), NOW()),
('tuta.com', 'DENIED', 'Tuta: Turn ON privacy for free with secure emails, calendars &amp; contacts | Tuta', NOW(), NOW()),
('gmx.com', 'DENIED', 'Free Email Accounts @GMX.com: Secure &amp; easy to use', NOW(), NOW()),
('gmx.us', 'DENIED', 'Free Email Accounts @GMX.com: Secure &amp; easy to use', NOW(), NOW()),
('gmx.net', 'DENIED', '[Fetch Failed] Gmx', NOW(), NOW()),
('gmx.de', 'DENIED', 'GMX - kostenlose E-Mail, Cloud, Nachrichten & Freemail', NOW(), NOW()),
('mail.com', 'DENIED', 'Free email accounts with mail.com | Log in here or register today', NOW(), NOW()),
('inbox.com', 'DENIED', 'Inbox.com - Premium email', NOW(), NOW()),
('fastmail.com', 'DENIED', 'Email and calendar made better | Fastmail', NOW(), NOW()),
('fastmail.fm', 'DENIED', 'Email and calendar made better | Fastmail', NOW(), NOW()),
('qq.com', 'DENIED', '[Fetch Failed] Qq', NOW(), NOW()),
('163.com', 'DENIED', '网易', NOW(), NOW()),
('126.com', 'DENIED', '126网易免费邮-你的专业电子邮局', NOW(), NOW()),
('naver.com', 'DENIED', 'NAVER', NOW(), NOW()),
('daum.net', 'DENIED', '[Fetch Failed] Daum', NOW(), NOW()),
('mail.ru', 'DENIED', '[Fetch Failed] Mail', NOW(), NOW()),
('bk.ru', 'DENIED', '[Fetch Failed] Bk', NOW(), NOW()),
('list.ru', 'DENIED', '[Fetch Failed] List', NOW(), NOW()),
('inbox.ru', 'DENIED', '[Fetch Failed] Inbox', NOW(), NOW()),
('rambler.ru', 'DENIED', 'Рамблер — медийный портал: новости России и мира, почта, поиск, погода', NOW(), NOW()),
('web.de', 'DENIED', '[Fetch Failed] Web', NOW(), NOW()),
('t-online.de', 'DENIED', 'News &amp; E-Mail bei t-online | Politik, Sport, Unterhaltung &amp; Ratgeber', NOW(), NOW()),
('libero.it', 'DENIED', 'Libero: Mail, Ricerca e News con aggiornamento quotidiano', NOW(), NOW()),
('virgilio.it', 'DENIED', 'Virgilio: Mail, Login, Ultime Notizie in tempo reale e tanto altro!', NOW(), NOW()),
('orange.fr', 'DENIED', '&#8205;', NOW(), NOW()),
('free.fr', 'DENIED', 'Free : offres internet Fibre, Wi-Fi 7, TV et ligne fixe sans engagement', NOW(), NOW()),
('laposte.net', 'DENIED', 'Laposte.net', NOW(), NOW()),
('comcast.net', 'DENIED', '[Fetch Failed] Comcast', NOW(), NOW()),
('verizon.net', 'DENIED', '[Fetch Failed] Verizon', NOW(), NOW()),
('att.net', 'DENIED', '[Fetch Failed] Att', NOW(), NOW()),
('sbcglobal.net', 'DENIED', '[Fetch Failed] Sbcglobal', NOW(), NOW()),
('cox.net', 'DENIED', 'Cox Residential Services | Official Site', NOW(), NOW()),
('charter.net', 'DENIED', 'Spectrum.net', NOW(), NOW()),
('earthlink.net', 'DENIED', '[Fetch Failed] Earthlink', NOW(), NOW()),
('juno.com', 'DENIED', '[Fetch Failed] Juno', NOW(), NOW()),
('optimum.net', 'DENIED', 'Optimum | Support & Customer Account Management Home', NOW(), NOW())
ON CONFLICT (domain_name) DO NOTHING;
