name: Deploy hc-frontend

on:
  push:
    branches:
      - main
    paths:
      - 'hc-frontend/**'
      - '.github/workflows/deploy-hc-frontend.yml'

jobs:
  deploy-hc-frontend:
    name: Deploy hc-frontend to Houseclay Host
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Transfer hc-frontend source code to Houseclay Host
        run: |
          echo "${{ secrets.FRONTEND_SECURITY_KEY }}" > zebra_key.pem
          chmod 600 zebra_key.pem
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no -i zebra_key.pem" hc-frontend ec2-user@${{ secrets.FRONTEND_HOST }}:/home/ec2-user/

      - name: Install pm2 on Houseclay Host
        run: |
          ssh -o StrictHostKeyChecking=no -i zebra_key.pem ec2-user@${{ secrets.FRONTEND_HOST }} << EOF
          sudo npm install -g pm2
          EOF

      - name: Build hc-frontend on Houseclay Host
        env:
          NEXT_PUBLIC_HOUSECLAY_API_BASE_URL: ${{ secrets.EC2_HOST }}:8080/api
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i zebra_key.pem ec2-user@${{ secrets.FRONTEND_HOST }} << EOF
          cd /home/ec2-user/hc-frontend
          rm -f .env.local
          echo "NEXT_PUBLIC_HOUSECLAY_API_BASE_URL=$EC2_HOST" >> .env.local
          echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY" >> .env.local
          npm install
          npm run build:prod
          EOF

      # Frontend server
      - name: Start hc-frontend on Houseclay Host
        run: |
          ssh -o StrictHostKeyChecking=no -i zebra_key.pem ec2-user@${{ secrets.FRONTEND_HOST }} << EOF
          cd /home/ec2-user/hc-frontend
          pm2 delete houseclay-ui-app || true
          pm2 start npm --name "houseclay-ui-app" -- start
          EOF
